#!/usr/bin/env python
from os import listdir
from os.path import isfile, join
import paramiko
from jinja2 import Environment, FileSystemLoader




ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
try:
    ssh.connect('localhost',username='',password='')
except paramiko.SSHException:
    print "Connection Failed"
    quit()

configdata = {}

stdin,stdout,stderr = ssh.exec_command("ls ~/GitHub/sshconfbuilder/sjc.foo.com")

for line in stdout.readlines():
    print line.strip()
    fqdn = line.strip()
    print fqdn
    a,b = fqdn.split('.')[:2]
    print a
ssh.close()

#mypath = "~/GitHub/sshconfbuilder/sjc.foo.com"
#nlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
#rint "ONLYFILES = "
#rint onlyfiles
