#!/usr/bin/env python
import os
import jinja2

lsFolders = [
    '/Users/jeffa/GitHub/sshconfbuilder/sjc.foo.com',
    '/Users/jeffa/GitHub/sshconfbuilder/sjc.foo.com',
    '/Users/jeffa/GitHub/sshconfbuilder/sjc.foo.com'
]

templateVars = {}

templateLoader = jinja2.FileSystemLoader( searchpath="/")
templateEnv = jinja2.Environment( loader=templateLoader )
TEMPLATE_FILE = "/Users/jeffa/GitHub/sshconfbuilder/sshConfigFile"
template = templateEnv.get_template( TEMPLATE_FILE )

for folder in lsFolders:
    targetFolder = 'ls ' + folder
    sshProcess = os.popen( targetFolder )
    lsOutput = sshProcess.read().strip().split()
    sshProcess.close()
    for fqdn_hostname in lsOutput:
        templateVars['fqdn_hostname'] = fqdn_hostname
        templateVars['host'], templateVars['datacenter'] = fqdn_hostname.split('.')[:2]
        outputText = template.render( templateVars )
        print outputText
